FROM node:alpine

# @see https://www.saltycrane.com/blog/2021/04/buildtime-vs-runtime-environment-variables-nextjs-docker/
ARG NEXT_PUBLIC_STRIPE_PUBLIC_KEY
ENV NEXT_PUBLIC_STRIPE_PUBLIC_KEY=$NEXT_PUBLIC_STRIPE_PUBLIC_KEY

ARG NEXT_PUBLIC_BASE_URI
ENV NEXT_PUBLIC_BASE_URI=$NEXT_PUBLIC_BASE_URI

WORKDIR /app
COPY package.json .
RUN npm install
COPY . .

ENV NODE_ENV production

RUN npm run build

CMD ["npm", "run", "start"]
