apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
  - image: torenware/ticketer-auth
    context: auth
    sync:
      manual:
      - src: src/***/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: torenware/ticketer-tickets
    context: tickets
    sync:
      manual:
      - src: src/***/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: torenware/ticketer-orders
    context: orders
    sync:
      manual:
      - src: src/***/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: torenware/ticketer-payments
    context: payments
    sync:
      manual:
      - src: src/***/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: torenware/ticketer-expiration
    context: expiration
    sync:
      manual:
      - src: src/***/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: torenware/ticketer-client
    context: client
    sync:
      manual:
      - src: '***/*.ts'
        dest: .
    docker:
      dockerfile: Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
