name: deploy-client

on:
  push:
    branches:
    - master
    paths:
    - 'client/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: >
           cd client &&
           docker build 
           --build-arg NEXT_PUBLIC_STRIPE_PUBLIC_KEY
           --build-arg NEXT_PUBLIC_BASE_URI
           --file Dockerfile-production
           -t torenware/ticketer-client .
      env:
        NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
        NEXT_PUBLIC_BASE_URI: ${{ secrets.BASE_URI }}
    - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push torenware/ticketer-client
    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
    - run: doctl kubernetes cluster kubeconfig save k8s-tware-sfo3-test-1
    - run: kubectl rollout restart deploy client-depl
    
