name: tests-expiration

on:
  pull_request:
    paths:
    - 'expiration/**'

  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd expiration && yarn install && yarn test:ci
    
